const ONE_DAY_MS = 24 * 60 * 60 * 1000;
const SESSION_DURATION_DAYS = 30;

export const SESSION_MAX_AGE_MS = SESSION_DURATION_DAYS * ONE_DAY_MS;

export const AUTH_CONSTRAINTS = {
  EMAIL_MAX_LENGTH: 255,
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 100,
  TOKEN_HASH_LENGTH: 64,
  IP_ADDRESS_MAX_LENGTH: 45,
} as const;
