import { ALLOWED_CONTENT_TYPES } from '@memoro/shared';

export const MEDIA_ACCEPT_ATTRIBUTE = ALLOWED_CONTENT_TYPES.join(',');

export const MEDIA_UPLOAD_LIMITS = {
  LOCATION_TOAST_DURATION_MS: 3000,
  SUCCESS_TOAST_DURATION_MS: 2000,
  ERROR_TOAST_DURATION_MS: 4000,
} as const;

export const MEDIA_UI_CONSTANTS = {
  EMPTY_ZONE_ICON_SIZE: 48,
  ACTION_ICON_SIZE: 20,
  PREVIEW_ICON_SIZE: 16,
  NAVIGATION_ICON_SIZE: 18,
} as const;
